
name: DestroyContainerDockerAwsEC2All

on:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Start AWS EC2

        run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: SSH connect
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AWS_INSTANCE_IP }}
            username: ${{ secrets.AWS_INSTANCE_USER }}
            key: ${{ secrets.AWS_SSH_KEY_PEM }}
            port: ${{ secrets.AWS_INSTANCE_SSH_PORT }}
            script: | 
              echo "remove all containers"
              sudo docker stop $(docker ps -a -q)
              echo "stop all containers by force"
              sudo docker kill $(docker ps -q)
              echo "remove all containers"
              sudo docker rm $(docker ps -a -q)
              echo "remove all docker images"
              sudo docker rmi $(docker images -q)
              echo "purge the rest"
              sudo docker system prune --all --force --volumes
              echo "remove folder"
              sudo rm -rf /home/${{ secrets.AWS_INSTANCE_USER }}/${{ github.event.repository.name }}